/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: "#00685f",
        "on-tertiary-container": "#f7fff2",
        "on-background": "#0b1c30",
        "secondary-fixed": "#eaddff",
        "tertiary-fixed-dim": "#62df7d",
        "surface-tint": "#006a61",
        "on-primary-container": "#f4fffc",
        "error-container": "#ffdad6",
        "surface-variant": "#d3e4fe",
        "on-secondary": "#ffffff",
        "inverse-surface": "#213145",
        "secondary": "#712ae2",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#6bd8cb",
        "on-tertiary": "#ffffff",
        "surface": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "on-secondary-container": "#fffbff",
        "surface-container-highest": "#d3e4fe",
        "inverse-primary": "#6bd8cb",
        "on-error": "#ffffff",
        "surface-container-high": "#dce9ff",
        "on-surface": "#0b1c30",
        "surface-container": "#e5eeff",
        "surface-container-low": "#eff4ff",
        "on-surface-variant": "#3d4947",
        "on-tertiary-fixed-variant": "#005320",
        "background": "#f8f9ff",
        "outline-variant": "#bcc9c6",
        "outline": "#6d7a77",
        "on-primary-fixed-variant": "#005049",
        "on-primary-fixed": "#00201d",
        "surface-bright": "#f8f9ff",
        "on-secondary-fixed": "#25005a",
        "on-error-container": "#93000a",
        "surface-dim": "#cbdbf5",
        "on-secondary-fixed-variant": "#5a00c6",
        "tertiary-container": "#00873a",
        "primary-fixed": "#89f5e7",
        "on-tertiary-fixed": "#002109",
        "tertiary-fixed": "#7ffc97",
        "inverse-on-surface": "#eaf1ff",
        "tertiary": "#006b2c",
        "secondary-container": "#8a4cfc",
        "on-primary": "#ffffff",
        "primary-container": "#008378",
        "secondary-fixed-dim": "#d2bbff",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}

