/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        // ----- Capy Squad rose/cream theme -----
        "capy-bg":         "#f3d4ce",
        "capy-card":       "#fce5dd",
        "capy-card-hi":    "#f4c5b5",
        "capy-sidebar":    "#f0d8d3",
        "capy-border":     "#e0bcb4",
        "capy-border-hi":  "#c98080",
        "capy-brown":      "#5a3826",
        "capy-brown-2":    "#8B5E3C",
        "capy-brown-3":    "#3d2b1f",
        "capy-amber":      "#c89060",
        "capy-amber-soft": "#fae5dd",
        "capy-rose":       "#c98080",
        "capy-rose-soft":  "#e8b8b0",
        "capy-active":     "#d99a9a",
        "capy-success":    "#6ba66c",
        "capy-success-soft": "#c8e0b8",
        "capy-warn":       "#d4a065",
        "capy-danger":     "#dc2626",
        "capy-text":       "#3d2b1f",
        "capy-muted":      "#8a6a55",
        "capy-muted-2":    "#b07878",
        "capy-hover":      "#ecc8c0",

        // legacy spine-* aliases
        "spine-bg":        "#f3d4ce",
        "spine-card":      "#fce5dd",
        "spine-card-hi":   "#f4c5b5",
        "spine-border":    "#e0bcb4",
        "spine-purple":    "#5a3826",
        "spine-purple-2":  "#c89060",
        "spine-purple-bg": "#fae5dd",
        "spine-success":   "#6ba66c",
        "spine-warn":      "#d4a065",
        "spine-danger":    "#dc2626",
        "spine-text":      "#3d2b1f",
        "spine-muted":     "#8a6a55",
        "spine-muted-2":   "#b07878",

        // semantic remap
        primary:                       "#5a3826",
        "on-primary":                  "#fce5dd",
        "primary-container":           "#8B5E3C",
        "on-primary-container":        "#fce5dd",
        "primary-fixed":               "#e0bcb4",
        "primary-fixed-dim":           "#c89060",
        "on-primary-fixed":            "#3d2b1f",
        "on-primary-fixed-variant":    "#5a3826",

        secondary:                     "#c89060",
        "on-secondary":                "#ffffff",
        "secondary-container":         "#fae5dd",
        "on-secondary-container":      "#5a3826",
        "secondary-fixed":             "#fae5dd",
        "secondary-fixed-dim":         "#d4a065",
        "on-secondary-fixed":          "#3d2b1f",
        "on-secondary-fixed-variant":  "#5a3826",

        tertiary:                      "#6ba66c",
        "on-tertiary":                 "#ffffff",
        "tertiary-container":          "#c8e0b8",
        "on-tertiary-container":       "#2c3a1d",
        "tertiary-fixed":              "#6ba66c",
        "tertiary-fixed-dim":          "#6ba66c",
        "on-tertiary-fixed":           "#1a2810",
        "on-tertiary-fixed-variant":   "#3a5a30",

        error:                         "#dc2626",
        "on-error":                    "#ffffff",
        "error-container":             "#f5d4cb",
        "on-error-container":          "#5a1a0a",

        background:                    "#f3d4ce",
        "on-background":               "#3d2b1f",
        surface:                       "#f3d4ce",
        "surface-tint":                "#5a3826",
        "surface-bright":              "#fce5dd",
        "surface-dim":                 "#f0d8d3",
        "surface-container-lowest":    "#fff7f3",
        "surface-container-low":       "#fce5dd",
        "surface-container":           "#f7d8cf",
        "surface-container-high":      "#f0d8d3",
        "surface-container-highest":   "#e8c8c0",
        "on-surface":                  "#3d2b1f",
        "on-surface-variant":          "#8a6a55",
        "inverse-surface":             "#3d2b1f",
        "inverse-on-surface":          "#fce5dd",
        "inverse-primary":             "#e0bcb4",

        outline:                       "#e0bcb4",
        "outline-variant":             "#e0bcb4",

        // ----- Legacy Theme Colors -----
        "legacy-primary": "#00685f",
        "legacy-bg": "#f8f9ff",
        "legacy-on-surface": "#0b1c30",
        "legacy-surface-low": "#eff4ff",
        "legacy-surface-container": "#e5eeff",
        "legacy-surface-lowest": "#ffffff",

        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        foreground: "hsl(var(--foreground))",
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
    },
  },
  plugins: [],
}
